Index:
    pattern:  /
    defaults: { _controller: CrystalNewsBundle:Views:index }

listUsers:
    pattern:   /admin/listUsers
    defaults:  { _controller: CrystalNewsBundle:users:list }

addUsers:
    pattern:   /userList/addUsers
    defaults:  { _controller: CrystalNewsBundle:users:add }

updateUsers:
    pattern:   /admin/updateUsers/{id}
    defaults:  { _controller: CrystalNewsBundle:users:update }

deleteUsers:
    pattern:   /admin/deleteUsers/{id}
    defaults:  { _controller: CrystalNewsBundle:users:delete }

addAccess:
    pattern:   /admin/addAccess/{id}
    defaults:  { _controller: CrystalNewsBundle:access:add }

listCategories:
    pattern:   /admin/listCategories
    defaults:  { _controller: CrystalNewsBundle:categories:list }

addCategories:
    pattern:   /userList/addCategories
    defaults:  { _controller: CrystalNewsBundle:categories:add }

updateCategories:
    pattern:   /admin/updateCategories/{id}
    defaults:  { _controller: CrystalNewsBundle:categories:update }

deleteCategories:
    pattern:   /admin/deleteCategories/{id}
    defaults:  { _controller: CrystalNewsBundle:categories:delete }





