Index:
    pattern:  /
    defaults: { _controller: CrystalNewsBundle:Views:index }

userlist:
    pattern:   /userlist
    defaults:  { _controller: CrystalNewsBundle:users:list }

register:
    pattern:   /registrate
    defaults:  { _controller: CrystalNewsBundle:users:register }