Index:
    pattern:  /
    defaults: { _controller: CrystalNewsBundle:Views:index }

userlist:
    pattern:   /userlist
    defaults:  { _controller: CrystalNewsBundle:users:list }

register:
    pattern:   /register
    defaults:  { _controller: CrystalNewsBundle:users:register }

updateUsers:
    pattern:   /admin/updateUsers/{id}
    defaults:  { _controller: CrystalNewsBundle:users:update }

deleteUsers:
    pattern:   /admin/deleteUsers/{id}
    defaults:  { _controller: CrystalNewsBundle:users:delete }

addAccess:
    pattern:   /admin/addAccess
    defaults:  { _controller: CrystalNewsBundle:access:add }

<<<<<<< HEAD
createNews:
    pattern:   /admin/createNews
    defaults:  { _controller: CrystalNewsBundle:news:add }
=======
listCategories:
    pattern:   /admin/listCategories
    defaults:  { _controller: CrystalNewsBundle:categories:list }

addCategories:
    pattern:   /userList/addCategories
    defaults:  { _controller: CrystalNewsBundle:categories:add }

updateCategories:
    pattern:   /admin/updateCategories/{id}
    defaults:  { _controller: CrystalNewsBundle:categories:update }

deleteCategories:
    pattern:   /admin/deleteCategories/{id}
    defaults:  { _controller: CrystalNewsBundle:categories:delete }

<<<<<<< HEAD
>>>>>>> 21f7406c1dba8180e8430b9b2ef370b2903eb530
=======
<<<<<<< HEAD
listMultimedia:
    pattern:   /admin/listMultimedia
    defaults:  { _controller: CrystalNewsBundle:multimedia:list }

addMultimedia:
    pattern:   /userList/addMultimedia
    defaults:  { _controller: CrystalNewsBundle:multimedia:add }

updateMultimedia:
    pattern:   /admin/updateMultimedia/{id}
    defaults:  { _controller: CrystalNewsBundle:multimedia:update }

deleteMultimedia:
    pattern:   /admin/deleteMultimedia/{id}
    defaults:  { _controller: CrystalNewsBundle:multimedia:delete }
=======
>>>>>>> c20951191328bc2be6b07243c73cd474bab5296a
>>>>>>> e3b4ac5f91289c61c6ed2cfd774cc5842a50669e




