Index:
    pattern:  /
    defaults: { _controller: CrystalNewsBundle:Views:index }

userlist:
    pattern:   /lista
    defaults:  { _controller: CrystalNewsBundle:Users:list }

register:
    pattern:   /registrate
    defaults:  { _controller: CrystalNewsBundle:Users:register }

validateUser:
    pattern:   /validateUser
    defaults:  { _controller: CrystalNewsBundle:Users:validateUser }