<?php

namespace Crystal\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * catCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catCategoriesRepository extends EntityRepository
{
}
