addAccess:
    pattern:   /admin/addAccess
    defaults:  { _controller: CrystalAdminBundle:access:add }

listNews:
    pattern:   /admin/listNews
    defaults:  { _controller: CrystalAdminBundle:news:list }

createNews:
    pattern:   /admin/createNews
    defaults:  { _controller: CrystalAdminBundle:news:add }

updateNews:
    pattern:   /admin/updateNews/{id}
    defaults:  { _controller: CrystalAdminBundle:news:update }

deleteNews:
    pattern:   /admin/deleteNews/{id}
    defaults:  { _controller: CrystalAdminBundle:news:delete }

listCategories:
    pattern:   /admin/listCategories
    defaults:  { _controller: CrystalAdminBundle:categories:list }


addCategories:
    pattern:   /admin/addCategories
    defaults:  { _controller: CrystalAdminBundle:categories:add }

updateCategories:
    pattern:   /admin/updateCategories/{id}
    defaults:  { _controller: CrystalAdminBundle:categories:update }

deleteCategories:
    pattern:   /admin/deleteCategories/{id}
    defaults:  { _controller: CrystalAdminBundle:categories:delete }

listMultimedia:
    pattern:   /admin/listMultimedia
    defaults:  { _controller: CrystalAdminBundle:multimedia:list }

addMultimedia:
    pattern:   /userList/addMultimedia
    defaults:  { _controller: CrystalAdminBundle:multimedia:add }

updateMultimedia:
    pattern:   /admin/updateMultimedia/{id}
    defaults:  { _controller: CrystalAdminBundle:multimedia:update }

deleteMultimedia:
    pattern:   /admin/deleteMultimedia/{id}
    defaults:  { _controller: CrystalAdminBundle:multimedia:delete }

adminControlPanel:
    pattern: /admin/adminViews
    defaults: { _controller: CrystalAdminBundle:adminViews:index }

login:
    pattern: /admin
    defaults: { _controller: CrystalAdminBundle:access:login }


